Repository School-of-Company/Bitgouel-iOS, pull requests merged in 2023-10, with the labels that each got.

#2 tuist setting
  .gitignore
  App/Project.swift
  App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  App/Resources/Assets.xcassets/Contents.json
  App/Resources/LaunchScreen.storyboard
  App/Sources/Application/DI/RemoveMe1.swift
  App/Sources/Presentation/RemoveMe5.swift
  App/Support/Info.plist
  App/Tests/TargetTest.swift
  LICENSE
  Makefile
  Service/Project.swift
  Service/Sources/Data/Repository/RemoveMe2.swift
  Service/Sources/Data/UseCase/Removeme3.swift
  Service/Sources/Domain/RemoveMe4.swift
  ThirdPartyLib/Project.swift
  ThirdPartyLib/Sources/RemoveMe6.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/DynamicFramwork.swift
  Tuist/ProjectDescriptionHelpers/Executable.swift
  Tuist/ProjectDescriptionHelpers/OrganizationName.swift
  Tuist/ProjectDescriptionHelpers/ProjectDeployTarget.swift
  Tuist/ProjectDescriptionHelpers/Settings.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  Workspace.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting, 🪡 Want

#4 :memo: :: ReadMe 작성
  README.md
Labels: 1️⃣ Priority: High, ⚡️ Simple, 📝 Docs, 🪡 Want

#6 💚 :: CI 스크립트 작성
  .github/workflows/bitgouel-ios-ci.yml
  App/Sources/Application/BitgouelApp.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#11 🔀 :: FontSystem추가
  App/Resources/Font/Pretendard-Regular.otf
  App/Resources/Font/Pretendard-SemiBold.otf
  App/Sources/DesignSystem/Font/BitgouelFontable.swift
  App/Sources/DesignSystem/Font/Font+Bitgouel.swift
Labels: 1️⃣ Priority: High, ⚙ Setting, ✨ Feature

#16 🔀 :: SwiftLint, SwiftFormat 설정
  .swiftformat
  .swiftlint.yml
  Scripts/.swiftformat
  Scripts/.swiftlint.yml
  Scripts/Setup.sh
  Tuist/ProjectDescriptionHelpers/DynamicFramwork.swift
  Tuist/ProjectDescriptionHelpers/Executable.swift
  Tuist/ProjectDescriptionHelpers/Scripts.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#14 🔀 :: ColorSystem 추가
  App/Resources/Color/Error.xcassets/Contents.json
  App/Resources/Color/Error.xcassets/E1.colorset/Contents.json
  App/Resources/Color/Error.xcassets/E2.colorset/Contents.json
  App/Resources/Color/Error.xcassets/E3.colorset/Contents.json
  App/Resources/Color/Error.xcassets/E4.colorset/Contents.json
  App/Resources/Color/Error.xcassets/E5.colorset/Contents.json
  App/Resources/Color/Error.xcassets/E6.colorset/Contents.json
  App/Resources/Color/Error.xcassets/E7.colorset/Contents.json
  App/Resources/Color/Error.xcassets/E8.colorset/Contents.json
  App/Resources/Color/Error.xcassets/E9.colorset/Contents.json
  App/Resources/Color/Greyscale.xcassets/Contents.json
  App/Resources/Color/Greyscale.xcassets/G1.colorset/Contents.json
  App/Resources/Color/Greyscale.xcassets/G2.colorset/Contents.json
  App/Resources/Color/Greyscale.xcassets/G3.colorset/Contents.json
  App/Resources/Color/Greyscale.xcassets/G4.colorset/Contents.json
  App/Resources/Color/Greyscale.xcassets/G5.colorset/Contents.json
  App/Resources/Color/Greyscale.xcassets/G6.colorset/Contents.json
  App/Resources/Color/Greyscale.xcassets/G7.colorset/Contents.json
  App/Resources/Color/Greyscale.xcassets/G8.colorset/Contents.json
  App/Resources/Color/Greyscale.xcassets/G9.colorset/Contents.json
  App/Resources/Color/Primary.xcassets/Contents.json
  App/Resources/Color/Primary.xcassets/P1.colorset/Contents.json
  App/Resources/Color/Primary.xcassets/P2.colorset/Contents.json
  App/Resources/Color/Primary.xcassets/P3.colorset/Contents.json
  App/Resources/Color/Primary.xcassets/P4.colorset/Contents.json
  App/Resources/Color/Primary.xcassets/P5.colorset/Contents.json
  App/Resources/Color/Primary.xcassets/P6.colorset/Contents.json
  App/Resources/Color/Primary.xcassets/P7.colorset/Contents.json
  App/Resources/Color/Primary.xcassets/P8.colorset/Contents.json
  App/Resources/Color/Primary.xcassets/P9.colorset/Contents.json
  App/Resources/Color/Sub.xcassets/Contents.json
  App/Resources/Color/Sub.xcassets/S1.colorset/Contents.json
  App/Resources/Color/Sub.xcassets/S2.colorset/Contents.json
  App/Resources/Color/Sub.xcassets/S3.colorset/Contents.json
  App/Resources/Color/Sub.xcassets/S4.colorset/Contents.json
  App/Resources/Color/Sub.xcassets/S5.colorset/Contents.json
  App/Resources/Color/Sub.xcassets/S6.colorset/Contents.json
  App/Resources/Color/Sub.xcassets/S7.colorset/Contents.json
  App/Resources/Color/Sub.xcassets/S8.colorset/Contents.json
  App/Resources/Color/Sub.xcassets/S9.colorset/Contents.json
  App/Sources/DesignSystem/Color/BitgouelColor+Error.swift
  App/Sources/DesignSystem/Color/BitgouelColor+Greyscale.swift
  App/Sources/DesignSystem/Color/BitgouelColor+Primary.swift
  App/Sources/DesignSystem/Color/BitgouelColor+Sub.swift
  App/Sources/DesignSystem/Color/BitgouelColorable.swift
  App/Sources/DesignSystem/Color/Color+Bitgouel.swift
Labels: 1️⃣ Priority: High, ⚙ Setting, ✨ Feature

#19 🔀 :: [#18] DesignSystem / Font에 color 설정 기능 추가
  App/Sources/DesignSystem/Font/Font+Bitgouel.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#17 🔀 :: [#12] DesignSystem / BitgouelText 제작
  App/Sources/DesignSystem/Text/BitgouelText.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#26 🔀 :: [#22] BaseRemoteDataSource 세팅
  App/Sources/Application/DI/RemoveMe1.swift
  App/Sources/DesignSystem/Color/Color+Bitgouel.swift
  App/Sources/DesignSystem/Font/Font+Bitgouel.swift
  App/Sources/DesignSystem/Text/BitgouelText.swift
  App/Sources/Presentation/RemoveMe5.swift
  App/Tests/TargetTest.swift
  Service/Sources/Base/API/RefreshAPI.swift
  Service/Sources/Base/BitgoeulAPI.swift
  Service/Sources/Base/DataSource/BaseRemoteDataSource.swift
  Service/Sources/Base/Error/RefreshError.swift
  Service/Sources/Base/Plugins/Jwt/JwtAuthorizable.swift
  Service/Sources/Base/Plugins/Jwt/JwtPlugin.swift
  Service/Sources/Base/Plugins/Jwt/TokenDTO.swift
  Service/Sources/Base/Plugins/Logging/MoyaLoggingPlugin.swift
  Service/Sources/Data/Repository/RemoveMe2.swift
  Service/Sources/Domain/RemoveMe4.swift
  Service/Sources/Keychain/Sources/Keychain.swift
  Service/Sources/Keychain/Sources/KeychainFake.swift
  Service/Sources/Keychain/Sources/KeychainImpl.swift
  ThirdPartyLib/Project.swift
  ThirdPartyLib/Sources/RemoveMe6.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/DynamicFramwork.swift
  Tuist/ProjectDescriptionHelpers/Executable.swift
  Tuist/ProjectDescriptionHelpers/ProjectDeployTarget.swift
  Tuist/ProjectDescriptionHelpers/Scripts.swift
  Tuist/ProjectDescriptionHelpers/Settings.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: 1️⃣ Priority: High, ⚙ Setting, ✨ Feature

#25 :twisted_rightwards_arrows: :: [#24] DesignSystem에 TextField 추가
  App/Resources/Assets.xcassets/cancel.imageset/Bitgoeul Cancel.svg
  App/Resources/Assets.xcassets/cancel.imageset/Contents.json
  App/Resources/Assets.xcassets/eye.imageset/Contents.json
  App/Resources/Assets.xcassets/eye.imageset/eye.svg
  App/Resources/Assets.xcassets/eye_slash.imageset/Contents.json
  App/Resources/Assets.xcassets/eye_slash.imageset/eye.slash.svg
  App/Sources/DesignSystem/TextField/BitgoeulTextField.swift
  App/Sources/DesignSystem/TextField/SecureBitgoeulTextField.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#27 🔀 ::[#23] DesignSystem에 Button 추가
  App/Sources/DesignSystem/Button/BitgouelButton.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#31 🔀 :: [#29] AuthDomain 세팅
  App/Sources/DesignSystem/Color/Color+Bitgouel.swift
  App/Sources/DesignSystem/TextField/BitgoeulTextField.swift
  App/Sources/DesignSystem/TextField/SecureBitgoeulTextField.swift
  Service/Sources/Base/API/RefreshAPI.swift
  Service/Sources/Base/BitgoeulAPI.swift
  Service/Sources/Base/DataSource/BaseRemoteDataSource.swift
  Service/Sources/Base/Enum/ApproveStatusType.swift
  Service/Sources/Base/Enum/FeedType.swift
  Service/Sources/Base/Enum/HighSchoolType.swift
  Service/Sources/Base/Enum/UserRoleType.swift
  Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
  Service/Sources/Domain/AuthDomain/DTO/Request/CompanyInstructorSignupRequestDTO.swift
  Service/Sources/Domain/AuthDomain/DTO/Request/GrovernmentSignupRequestDTO.swift
  Service/Sources/Domain/AuthDomain/DTO/Request/LoginRequestDTO.swift
  Service/Sources/Domain/AuthDomain/DTO/Request/ProfessorSignupRequestDTO.swift
  Service/Sources/Domain/AuthDomain/DTO/Request/StudentSignupRequestDTO.swift
  Service/Sources/Domain/AuthDomain/DTO/Request/TeacherSignupRequestDTO.swift
  Service/Sources/Domain/AuthDomain/DataSource/LocalAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/Error/AuthDomainError.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/RemoveMe4.swift
  Tuist/Dependencies.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#33 🔀 :: [#21] 학생 회원가입 기능 추가
  App/Sources/DesignSystem/Button/BitgouelButton.swift
  Service/Sources/Base/BitgouelAPI.swift
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/Repository/RemoveMe2.swift
  Service/Sources/Data/UseCase/Auth/StudentSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Removeme3.swift
  Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/AuthDomain/UseCase/StudentSignupUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#39 🔀:: [#38] 로그아웃 기능 추가
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/LogoutUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/AuthDomain/UseCase/LogoutUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#35 🔀 :: [#34] 로그인 기능 추가
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/LoginUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/AuthDomain/UseCase/LoginUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#37 🔀 :: [#36] 토큰 재발급 기능 추가
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/ReissueTokenUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/AuthDomain/UseCase/ReissueTokenUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#46 🔀 :: [#45] 대학교수 회원가입 기능 추가
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/ProfessorSignupUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/AuthDomain/UseCase/ProfessorSignupUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#49 🔀 :: [#47] 유관 기관 회원가입 기능 추가
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/GovernmentSignupUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
  Service/Sources/Domain/AuthDomain/DTO/Request/GovernmentSignupRequestDTO.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/AuthDomain/UseCase/GovernmentSignupUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#52 🔀 :: [#51] 기업 강사 회원가입 기능 추가
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/CompanyInstructorSignupUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/AuthDomain/UseCase/CompanyInstructorSignupUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature
