Repository School-of-Company/Bitgouel-iOS, pull requests merged in 2023-11, with the labels that each got.

#50 🔀 :: [#48] Button에 Secondary 추가
  App/Sources/DesignSystem/Button/BitgouelButton.swift
  App/Sources/DesignSystem/Button/BitgouelButtonStyle.swift
  App/Sources/DesignSystem/Extension/View+buttonWrapper.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#56 🔀 :: [#55] LectureDomain 세팅
  Service/Sources/Base/Enum/LectureType.swift
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureOpenUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
  Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
  Service/Sources/Domain/LectureDomain/DTO/Request/LectureOpenRequestDTO.swift
  Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
  Service/Sources/Domain/LectureDomain/Error/LectureDomainError.swift
  Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureOpenUseCase.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting, ✨ Feature

#58 🔀 :: [#57] 강의 개설 기능 추가
  App/Sources/DesignSystem/Button/BitgouelButton.swift
  App/Sources/DesignSystem/Button/BitgouelButtonStyle.swift
  Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureOpenUseCaseImpl.swift
  Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
  Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureOpenUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#61 🔀 :: [#32] DesignSystem에 BottomSheet 추가
  App/Sources/DesignSystem/BottomSheet/BitgouelBottomSheet.swift
  App/Sources/DesignSystem/Extensions/Environment+safeAreaInsets.swift
  App/Sources/DesignSystem/Extensions/View+buttonWrapper.swift
  App/Sources/DesignSystem/Extensions/View+cornerRadius.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#60 🔀 :: [#9] LoginPage 퍼블리싱
  App/Sources/DesignSystem/TextField/BitgoeulTextField.swift
  App/Sources/DesignSystem/TextField/SecureBitgoeulTextField.swift
  App/Sources/Feature/LoginFeature/LoginView.swift
  App/Sources/Feature/LoginFeature/LoginViewModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#63 🔀 :: [#59] LectureDomain 기능 추가
  App/Sources/DesignSystem/BottomSheet/BitgouelBottomSheet.swift
  App/Sources/DesignSystem/Extensions/View+cornerRadius.swift
  Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureApplyUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/WaitingLectureApproveUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/WaitingLectureRejectUseCaseImpl.swift
  Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
  Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
  Service/Sources/Domain/LectureDomain/Error/LectureDomainError.swift
  Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureApplyUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/WaitingLectureRejectUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/WaitingLectureUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#62 🔀 :: [#42] DesignSystem에 RadioButton 추가
  App/Sources/DesignSystem/Button/BitgouelButton/BitgouelButton.swift
  App/Sources/DesignSystem/Button/BitgouelButton/BitgouelButtonStyle.swift
  App/Sources/DesignSystem/Button/RadioButton/BitgouelRadioButton.swift
  App/Sources/DesignSystem/Button/RadioButton/PressedSelectionButtonStyle.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#68 🔀 :: [#67] DesignSystem에 ListSelectButton 추가
  App/Sources/DesignSystem/Button/ListSelectButton/AssociationSelectButton.swift
  App/Sources/DesignSystem/Button/ListSelectButton/AssociationSelectButtonStyle.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#70 🔀 :: [#69] 뽀짝쌤 회원가입 기능 추가
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/BbozzakSignupUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
  Service/Sources/Domain/AuthDomain/DTO/Request/BbozzakSignupRequestDTO.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/AuthDomain/UseCase/BbozzakSignupUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#72 🔀 :: [#71] BaseURL 세팅
  .gitignore
  Tuist/ProjectDescriptionHelpers/DynamicFramwork.swift
  Tuist/ProjectDescriptionHelpers/Executable.swift
  Tuist/ProjectDescriptionHelpers/PathExtension.swift
  Tuist/ProjectDescriptionHelpers/Settings.swift
  XCConfig/Shared.xcconfig
Labels: 0️⃣ Priority: Critical, ✨ Feature

#74 🔀 :: [#73] 강의 조회 기능 추가
  App/Sources/DesignSystem/Button/ListSelectButton/AssociationSelectButton.swift
  App/Sources/DesignSystem/Button/ListSelectButton/AssociationSelectButtonStyle.swift
  App/Sources/DesignSystem/Button/RadioButton/BitgouelRadioButton.swift
  App/Sources/DesignSystem/Button/RadioButton/PressedSelectionButtonStyle.swift
  App/Sources/DesignSystem/TextField/BitgoeulTextField.swift
  App/Sources/DesignSystem/TextField/SecureBitgoeulTextField.swift
  App/Sources/Feature/LoginFeature/LoginView.swift
  App/Sources/Feature/LoginFeature/LoginViewModel.swift
  Service/Sources/Base/Enum/LectureStatusType.swift
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/BbozzakSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureDetailInquiryUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureListInquirtyUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
  Service/Sources/Domain/AuthDomain/DTO/Request/BbozzakSignupRequestDTO.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureDeailResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureListResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
  Service/Sources/Domain/LectureDomain/Entity/LectureDetailEntity.swift
  Service/Sources/Domain/LectureDomain/Entity/LectureListEntity.swift
  Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureDetailInquiryUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureListInquirtyUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#77 Test Tuist verbose 옵션 추가
  .github/workflows/bitgouel-ios-ci.yml
Labels: ⚡️ Simple, ✅ Test

#81 🔀 :: HelpMessage 따로 분리
  App/Sources/Application/BitgouelApp.swift
  App/Sources/Feature/LoginFeature/LoginViewModel.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#78 🔀 :: [#65] CommonSighUpPage 퍼블리싱
  App/Sources/DesignSystem/Button/AssociationSelectButton/AssociationsSelectButton.swift
  App/Sources/DesignSystem/Button/AssociationSelectButton/AssociationsSelectButtonStyle.swift
  App/Sources/Feature/CommonSignUpFeature/CommonSignUpView.swift
  App/Sources/Feature/CommonSignUpFeature/CommonSignUpViewModel.swift
  Service/Sources/Base/Enum/AssociationType.swift
  Service/Sources/Base/Enum/UserRoleType.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#87 🔀 :: [#86] BitgouelButton의 생성자 수정
  App/Sources/DesignSystem/Button/BitgouelButton/BitgouelButton.swift
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#90 🔀 :: [#89] BaseFeature 세팅
  App/Sources/Feature/BaseFeature/BaseViewModel.swift
  App/Sources/Feature/BaseFeature/Flow/SceneFlow.swift
  App/Sources/Feature/BaseFeature/Flow/TabFlow.swift
  App/Sources/Feature/CommonSignUpFeature/CommonSignUpViewModel.swift
  App/Sources/Feature/LoginFeature/LoginViewModel.swift
  App/Sources/Feature/StudentSignUpFeature/StudentSignUpViewModel.swift
  Service/Sources/Data/UseCase/Auth/GovernmentSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/LoginUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/UseCase/GovernmentSignupUseCase.swift
  ThirdPartyLib/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting, ✨ Feature
