Repository School-of-Company/Bitgouel-iOS, pull requests merged in 2023-12, with the labels that each got.

#88 🔀 :: [#75] 로그인 버튼 API 연결
  App/Sources/Application/BitgouelApp.swift
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/DI/Auth/AppComponent+Auth.swift
  App/Sources/Application/DI/RemoveMe1.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/BaseFeature/Flow/SceneFlow.swift
  App/Sources/Feature/BaseFeature/Sources/SceneState.swift
  App/Sources/Feature/LoginFeature/Interface/LoginFactory.swift
  App/Sources/Feature/LoginFeature/Sources/LoginComponent.swift
  App/Sources/Feature/LoginFeature/Sources/LoginView.swift
  App/Sources/Feature/LoginFeature/Sources/LoginViewModel.swift
  App/Sources/Feature/RootFeature/RootComponent.swift
  App/Sources/Feature/RootFeature/RootView.swift
  App/Sources/Utils/Extensions/View+eraseToAnyView.swift
  App/Support/Info.plist
  Scripts/NeedleRunScript.sh
  Service/Project.swift
  Service/Sources/Base/BitgouelAPI.swift
  Service/Sources/Base/DataSource/BaseRemoteDataSource.swift
  Service/Sources/Data/DataSource/Auth/LocalAuthDataSourceImpl.swift
  Service/Sources/Data/DataSource/Auth/RemoteDataSourceImpl.swift
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/BbozzakSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/CompanyInstructorSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/GovernmentSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/LoginUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/LogoutUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/ProfessorSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/ReissueTokenUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/StudentSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/TeacherSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/WithdrawalUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/DataSource/LocalAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  ThirdPartyLib/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/DynamicFramwork.swift
  Tuist/ProjectDescriptionHelpers/Executable.swift
  Tuist/ProjectDescriptionHelpers/Scripts.swift
Labels: 0️⃣ Priority: Critical

#92 🔀 :: [#82] 강의 목록, 상세 페이지 퍼블리싱
  App/Resources/Icon/Icons.xcassets/check_stroke.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/check_stroke.imageset/check_stroke.svg
  App/Resources/Icon/Icons.xcassets/filter_stroke.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/filter_stroke.imageset/filter_stroke.svg
  App/Sources/DesignSystem/Alert/BitgouelAlert.swift
  App/Sources/DesignSystem/Alert/BitgouelAlertButtonType.swift
  App/Sources/DesignSystem/Button/BitgouelButton/BitgouelButtonStyle.swift
  App/Sources/DesignSystem/Button/CTAButton/CTAButton.swift
  App/Sources/DesignSystem/Button/CTAButton/CTAButtonStyle.swift
  App/Sources/DesignSystem/Button/CheckButton/CheckButton.swift
  App/Sources/DesignSystem/Color/BitgouelColor+Greyscale.swift
  App/Sources/DesignSystem/Extensions/View+navigate.swift
  App/Sources/DesignSystem/Toast/BitgouelToast.swift
  App/Sources/Feature/LectureListDetailFeature/Interface/LectureListDetailFactory.swift
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailViewModel.swift
  App/Sources/Feature/LectureListFeature/LectureListView.swift
  App/Sources/Feature/LectureListFeature/LectureListViewModel.swift
  Service/Sources/Base/Enum/ApproveStatusType.swift
  Service/Sources/Base/Enum/LectureType.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#106 🔀 :: [#105] activitydomain에 activityentity추가
  App/Sources/Application/BitgouelApp.swift
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/Alert/BitgouelAlert.swift
  App/Sources/DesignSystem/Alert/BitgouelAlertButtonType.swift
  App/Sources/DesignSystem/Button/BitgouelButton/BitgouelButtonStyle.swift
  App/Sources/DesignSystem/Button/CTAButton/CTAButtonStyle.swift
  App/Sources/DesignSystem/Button/CheckButton/CheckButton.swift
  App/Sources/DesignSystem/Extensions/View+navigate.swift
  App/Sources/DesignSystem/Toast/BitgouelToast.swift
  App/Sources/Feature/BaseFeature/Sources/SceneState.swift
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailViewModel.swift
  App/Sources/Feature/LectureListFeature/LectureListView.swift
  App/Sources/Feature/LectureListFeature/LectureListViewModel.swift
  App/Sources/Feature/LoginFeature/Sources/LoginComponent.swift
  App/Sources/Feature/LoginFeature/Sources/LoginView.swift
  App/Sources/Feature/LoginFeature/Sources/LoginViewModel.swift
  App/Sources/Feature/RootFeature/RootView.swift
  Service/Sources/Data/DataSource/Auth/LocalAuthDataSourceImpl.swift
  Service/Sources/Data/DataSource/Auth/RemoteDataSourceImpl.swift
  Service/Sources/Domain/ActivityDomain/Entity/SingleActivityEntity.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting, ⚡️ Simple

#109 🔀 :: [#108] club domain 세팅
  App/Sources/Feature/StudentSignUpFeature/StudentSignUpView.swift
  Service/Sources/Base/BitgouelAPI.swift
  Service/Sources/Data/DataSource/Club/RemoteClubDataSourceImpl.swift
  Service/Sources/Data/Repository/Club/ClubRepositoryImpl.swift
  Service/Sources/Data/UseCase/Club/QueryClubDatailUseCaseImpl.swift
  Service/Sources/Data/UseCase/Club/QueryClubListUseCaseImpl.swift
  Service/Sources/Data/UseCase/Club/QueryStudentListByClubUseCaseImpl.swift
  Service/Sources/Domain/ClubDomain/API/ClubAPI.swift
  Service/Sources/Domain/ClubDomain/DTO/Response/ClubDetailResponseDTO.swift
  Service/Sources/Domain/ClubDomain/DTO/Response/ClubListResponseDTO.swift
  Service/Sources/Domain/ClubDomain/DTO/Response/StudentListByClubResponseDTO.swift
  Service/Sources/Domain/ClubDomain/DataSource/RemoteClubDataSource.swift
  Service/Sources/Domain/ClubDomain/Entity/ClubDetailEntity.swift
  Service/Sources/Domain/ClubDomain/Entity/ClubsEntity.swift
  Service/Sources/Domain/ClubDomain/Entity/SingleClubEntity.swift
  Service/Sources/Domain/ClubDomain/Entity/SingleStudentEntity.swift
  Service/Sources/Domain/ClubDomain/Entity/StudentsEntity.swift
  Service/Sources/Domain/ClubDomain/Error/ClubDomainError.swift
  Service/Sources/Domain/ClubDomain/Repository/ClubRepository.swift
  Service/Sources/Domain/ClubDomain/UseCase/QueryClubDetailUseCase.swift
  Service/Sources/Domain/ClubDomain/UseCase/QueryClubListUseCase.swift
  Service/Sources/Domain/ClubDomain/UseCase/QueryStudentListByClubUseCase.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting, ⚡️ Simple, ✨ Feature

#112 🔀 :: [#110] UserRole을 UserDefaults에 저장하도록 변경
  App/Sources/Application/DI/Auth/AppComponent+Auth.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/CommonSignUpFeature/CommonSignUpViewModel.swift
  App/Sources/Feature/LoginFeature/Sources/LoginComponent.swift
  App/Sources/Feature/LoginFeature/Sources/LoginViewModel.swift
  App/Sources/Feature/StudentSignUpFeature/StudentSignUpViewModel.swift
  Service/Sources/Base/Enum/UserAuthorityType.swift
  Service/Sources/Data/DataSource/Auth/LocalAuthDataSourceImpl.swift
  Service/Sources/Data/DataSource/Auth/RemoteDataSourceImpl.swift
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/LoadUserAuthorityUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/LoginUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/SaveUserAuthorityUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/DTO/Response/LoginResponseDTO.swift
  Service/Sources/Domain/AuthDomain/DataSource/LocalAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/Entity/UserLoginEntity.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/AuthDomain/UseCase/LoadUserAuthorityUseCase.swift
  Service/Sources/Domain/AuthDomain/UseCase/LoginUseCase.swift
  Service/Sources/Domain/AuthDomain/UseCase/SaveUserAuthorityUseCase.swift
  Service/Sources/Domain/ClubDomain/DTO/Response/StudentListByClubResponseDTO.swift
  Service/Sources/Domain/ClubDomain/Entity/SingleStudentEntity.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#115 🔀 :: [#95] 회원가입 API연결
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/DI/Auth/AppComponent+Auth.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/LoginFeature/Sources/LoginComponent.swift
  App/Sources/Feature/LoginFeature/Sources/LoginView.swift
  App/Sources/Feature/LoginFeature/Sources/LoginViewModel.swift
  App/Sources/Feature/StudentSignUpFeature/Interface/StudentSignUpFactory.swift
  App/Sources/Feature/StudentSignUpFeature/StudentSignUpComponent.swift
  App/Sources/Feature/StudentSignUpFeature/StudentSignUpView.swift
  App/Sources/Feature/StudentSignUpFeature/StudentSignUpViewModel.swift
  App/Sources/Feature/StudentSignUpFeature/View/SchoolListRowView.swift
  Service/Sources/Base/Enum/UserAuthorityType.swift
  Service/Sources/Data/UseCase/Auth/TeacherSignupUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/UseCase/TeacherSignupUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature
