Repository School-of-Company/Bitgouel-iOS, pull requests merged in 2024-03, with the labels that each got.

#198 🔀 :: [#197] 공지사항 - 공지사항 세부설정 페이지 추가
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeComponent.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeView.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeViewModel.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Interface/NoticeDetailSettingFactory.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingComponent.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingView.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingViewModel.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListComponent.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListViewModel.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#195 🔀 :: [#194] 공지사항 추가, 수정 페이지 퍼블리싱
  .github/workflows/bitgouel-ios-ci.yml
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/DI/Inquiry/AppComponent+Inquiry.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/InputNoticeFeature/Interface/InputNoticeFactory.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeComponent.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeView.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeViewModel.swift
  App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailView.swift
  App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailViewComponent.swift
  App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailViewModel.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Interface/NoticeDetailSettingFactory.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingComponent.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingView.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingViewModel.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListComponent.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListViewModel.swift
  Service/Sources/Base/BitgouelAPI.swift
  Service/Sources/Base/Enum/AnswerStatusType.swift
  Service/Sources/Data/DataSource/Inquiry/RemoteInquiryDataSourceImpl.swift
  Service/Sources/Data/Repository/Inquiry/InquiryRepositoryImpl.swift
  Service/Sources/Data/UseCase/Inquiry/DeleteInquiryByAdminUseCaseUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/DeleteMyInquiryUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/FetchInquiryByAdminUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/FetchInquiryDetailUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/FetchMyInquiryListUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/InputInquiryUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/ModifyMyInquiryUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/ReplyInquiryUseCaseImpl.swift
  Service/Sources/Domain/InquiryDomain/API/InquiryAPI.swift
  Service/Sources/Domain/InquiryDomain/DTO/Request/InputInquiryRequestDTO.swift
  Service/Sources/Domain/InquiryDomain/DTO/Response/FetchInquiryDetailResponseDTO.swift
  Service/Sources/Domain/InquiryDomain/DTO/Response/FetchInquiryListResponseDTO.swift
  Service/Sources/Domain/InquiryDomain/DataSource/RemoteInquiryDataSource.swift
  Service/Sources/Domain/InquiryDomain/Entity/InquiryDetailEntity.swift
  Service/Sources/Domain/InquiryDomain/Entity/InquiryInfoEntity.swift
  Service/Sources/Domain/InquiryDomain/Error/InquiryDomainError.swift
  Service/Sources/Domain/InquiryDomain/Repository/InquiryRepository.swift
  Service/Sources/Domain/InquiryDomain/UseCase/DeleteInquiryByAdminUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/DeleteMyInquiryUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/FetchInquiryByAdminUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/FetchInquiryDetailUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/FetchMyInquiryListUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/InputInquiryUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/ModifyMyInquiryUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/ReplyInquiryUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#188 🔀 :: [#187] 공지사항 - 공지사항 상세보기 페이지 퍼블리싱
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/View/DetailView.swift
  App/Sources/Feature/NoticeDetailFeature/Interface/NoticeDetailFactory.swift
  App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailView.swift
  App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailViewComponent.swift
  App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailViewModel.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListComponent.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListViewModel.swift
  App/Sources/Feature/SuccessSignUpFeature/Interface/SuccessSignUpFactory.swift
  App/Sources/Feature/SuccessSignUpFeature/Sources/SuccessSignUpComponent.swift
  App/Sources/Feature/SuccessSignUpFeature/SuccessSignUpView.swift
  Service/Sources/Base/DataSource/BaseRemoteDataSource.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#193 🔀 :: [#187] 공지사항 - 공지사항 상세보기 페이지 API 연결
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/View/DetailView.swift
  App/Sources/Feature/InputNoticeFeature/Interface/InputNoticeFactory.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeComponent.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeView.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeViewModel.swift
  App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailView.swift
  App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailViewComponent.swift
  App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailViewModel.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Interface/NoticeDetailSettingFactory.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingComponent.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingView.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingViewModel.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListComponent.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListViewModel.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#202 🔀 :: [#201] 이미지 이름에 들어간 한글 삭제
  App/Resources/Image/Images.xcassets/EVEDI.imageset/Contents.json
  App/Resources/Image/Images.xcassets/EVEDI.imageset/EVEDI.png
  App/Resources/Image/Images.xcassets/EVEDI.imageset/화면-캡처-2022-12-22-100001-removebg-preview 1_waifu2x_photo_noise1_scale 1.png
  App/Resources/Image/Images.xcassets/gwangju.imageset/Contents.json
  App/Resources/Image/Images.xcassets/gwangju.imageset/Gwangju.svg
  App/Resources/Image/Images.xcassets/gwangjuSoftwareMeisterHighSchool.imageset/Contents.json
  App/Resources/Image/Images.xcassets/gwangjuSoftwareMeisterHighSchool.imageset/GwangjuSoftWareMeisterHighSchool.png
  App/Resources/Image/Images.xcassets/smhrd.imageset/2021-06-041124299590110_개발원로고 1.png
  App/Resources/Image/Images.xcassets/smhrd.imageset/Contents.json
  App/Resources/Image/Images.xcassets/smhrd.imageset/smhrd.png
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#204 🔀 :: [#111] 탭바 세팅
  App/Resources/Icon/Icons.xcassets/home.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/home.imageset/home.svg
  App/Resources/Icon/Icons.xcassets/laptop.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/laptop.imageset/laptop.svg
  App/Resources/Icon/Icons.xcassets/message_fill.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/message_fill.imageset/message.svg
  App/Resources/Icon/Icons.xcassets/person3_fill.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/person3_fill.imageset/person3 1.svg
  App/Resources/Icon/Icons.xcassets/person3_fill.imageset/person3.svg
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
  App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingView.swift
  App/Sources/Feature/BaseFeature/Flow/SceneFlow.swift
  App/Sources/Feature/BaseFeature/Sources/TabbarHidden.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListView.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailView.swift
  App/Sources/Feature/EditPostFeature/Source/EditPostView.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityView.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationView.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeView.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
  App/Sources/Feature/LoginFeature/Sources/LoginView.swift
  App/Sources/Feature/LoginFeature/Sources/LoginViewModel.swift
  App/Sources/Feature/MainFeature/Interface/MainFactory.swift
  App/Sources/Feature/MainFeature/Source/ClubRoleView.swift
  App/Sources/Feature/MainFeature/Source/GovernmentView.swift
  App/Sources/Feature/MainFeature/Source/IntroduceView.swift
  App/Sources/Feature/MainFeature/Source/JobDetailView.swift
  App/Sources/Feature/MainFeature/Source/MainComponent.swift
  App/Sources/Feature/MainFeature/Source/MainView.swift
  App/Sources/Feature/MainFeature/Source/TabViewSources/ClubViews/AiFusionAndCompositeClubView.swift
  App/Sources/Feature/MainFeature/Source/TabViewSources/ClubViews/CultureIndustryClubView.swift
  App/Sources/Feature/MainFeature/Source/TabViewSources/ClubViews/EnergyIndustryClubView.swift
  App/Sources/Feature/MainFeature/Source/TabViewSources/ClubViews/FutureTransportClubView.swift
  App/Sources/Feature/MainFeature/Source/TabViewSources/ClubViews/MedicalHealthClubView.swift
  App/Sources/Feature/MainFeature/Source/TabViewSources/ClubsAndCompanysNameView.swift
  App/Sources/Feature/MainFeature/Source/TabViewSources/CompanyViews/AiFusionAndCompositeCompanyView.swift
  App/Sources/Feature/MainFeature/Source/TabViewSources/CompanyViews/CultureIndustryCompanyView.swift
  App/Sources/Feature/MainFeature/Source/TabViewSources/CompanyViews/EnergyIndustryCompanyView.swift
  App/Sources/Feature/MainFeature/Source/TabViewSources/CompanyViews/FutureTransportCompanyView.swift
  App/Sources/Feature/MainFeature/Source/TabViewSources/CompanyViews/MedicalHealthCompanyView.swift
  App/Sources/Feature/MainFeature/Source/UniversityView.swift
  App/Sources/Feature/MainTabFeature/Interface/MainTabFactory.swift
  App/Sources/Feature/MainTabFeature/Source/MainTabComponent.swift
  App/Sources/Feature/MainTabFeature/Source/MainTabView.swift
  App/Sources/Feature/MyPageFeature/Interface/MyPageFactory.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageComponent.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageView.swift
  App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailView.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingView.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
  App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingView.swift
  App/Sources/Feature/RootFeature/RootComponent.swift
  App/Sources/Feature/RootFeature/RootView.swift
  App/Sources/Utils/Tabbar/HideTabbar.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#206 🔀 :: [#205] 문의사항 리스트 페이지 퍼블리싱
  App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#209 🔀 :: [#205] 문의사항 리스트 API 연결
  App/Sources/Application/DI/Inquiry/AppComponent+Inquiry.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/InquiryListFeature/Source/Component/AnswerFilterPopup.swift
  App/Sources/Feature/InquiryListFeature/Source/Component/InquiryListRow.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListComponent.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListViewModel.swift
  Service/Sources/Base/Enum/AnswerStatusType.swift
  Service/Sources/Data/DataSource/Inquiry/RemoteInquiryDataSourceImpl.swift
  Service/Sources/Data/Repository/Inquiry/InquiryRepositoryImpl.swift
  Service/Sources/Data/UseCase/Inquiry/FetchInquiryByAdminUseCaseImpl.swift
  Service/Sources/Domain/InquiryDomain/API/InquiryAPI.swift
  Service/Sources/Domain/InquiryDomain/DTO/Response/FetchInquiryListResponseDTO.swift
  Service/Sources/Domain/InquiryDomain/DataSource/RemoteInquiryDataSource.swift
  Service/Sources/Domain/InquiryDomain/Entity/InquiryInfoEntity.swift
  Service/Sources/Domain/InquiryDomain/Repository/InquiryRepository.swift
  Service/Sources/Domain/InquiryDomain/UseCase/FetchInquiryByAdminUseCase.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#208 🔀 :: [#207] admin 도메인 세팅
  App/Sources/Application/DI/Admin/AppComponent+Admin.swift
  App/Sources/Application/NeedleGenerated.swift
  Service/Sources/Data/DataSource/Admin/RemoteAdminDataSourceImpl.swift
  Service/Sources/Data/Repository/Admin/AdminRespositoryImpl.swift
  Service/Sources/Data/UseCase/Admin/ApproveUserSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Admin/FetchUserDetailUseCaseImpl.swift
  Service/Sources/Data/UseCase/Admin/FetchUserListUseCaseImpl.swift
  Service/Sources/Data/UseCase/Admin/RejectUserSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Admin/WithdrawUserUseCaseImpl.swift
  Service/Sources/Domain/AdminDomain/API/AdminAPI.swift
  Service/Sources/Domain/AdminDomain/DTO/Response/UserDetailInfoResponseDTO.swift
  Service/Sources/Domain/AdminDomain/DTO/Response/UserInfoResponseDTO.swift
  Service/Sources/Domain/AdminDomain/DataSource/RemoteAdminDataSource.swift
  Service/Sources/Domain/AdminDomain/Entity/UserInfoEntity.swift
  Service/Sources/Domain/AdminDomain/Error/AdminDomainError.swift
  Service/Sources/Domain/AdminDomain/Repository/AdminRepository.swift
  Service/Sources/Domain/AdminDomain/UseCase/ApproveUserSignupUseCase.swift
  Service/Sources/Domain/AdminDomain/UseCase/FetchUserDetailUseCase.swift
  Service/Sources/Domain/AdminDomain/UseCase/FetchUserListUseCase.swift
  Service/Sources/Domain/AdminDomain/UseCase/RejectUserSignupUseCase.swift
  Service/Sources/Domain/AdminDomain/UseCase/WithdrawUserSignupUseCase.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting, ✨ Feature

#213 🔀 :: [#211] 공지사항 키워드 검색 바 추가
  App/Resources/Icon/Icons.xcassets/search.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/search.imageset/searchIcon 1.svg
  App/Resources/Icon/Icons.xcassets/search.imageset/searchIcon.svg
  App/Sources/Feature/InquiryListFeature/Source/Component/KeywordSearchBar.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListViewModel.swift
  App/Sources/Utils/Extensions/View+if.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#214 🔀 :: [#212] 문의사항 추가 페이지 퍼블리싱
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/InputInquiryFeature/Interface/InputInquiryFactory.swift
  App/Sources/Feature/InputInquiryFeature/Source/InputInquiryComponent.swift
  App/Sources/Feature/InputInquiryFeature/Source/InputInquiryView.swift
  App/Sources/Feature/InputInquiryFeature/Source/InputInquiryViewModel.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListComponent.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListViewModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#215 🔀 :: [#212] 문의사항 추가 페이지 API연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/InputInquiryFeature/Source/InputInquiryComponent.swift
  App/Sources/Feature/InputInquiryFeature/Source/InputInquiryView.swift
  App/Sources/Feature/InputInquiryFeature/Source/InputInquiryViewModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#217 🔀 :: [#216] 문의사항 상세보기 페이지 퍼블리싱
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/InputInquiryFeature/Source/InputInquiryComponent.swift
  App/Sources/Feature/InputInquiryFeature/Source/InputInquiryView.swift
  App/Sources/Feature/InputInquiryFeature/Source/InputInquiryViewModel.swift
  App/Sources/Feature/InquiryDetailFeature/Interface/InquiryDetailFactory.swift
  App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailComponent.swift
  App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailView.swift
  App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailViewModel.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListComponent.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListViewModel.swift
  Service/Sources/Domain/InquiryDomain/DTO/Response/FetchInquiryDetailResponseDTO.swift
  Service/Sources/Domain/InquiryDomain/Entity/InquiryDetailEntity.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#218 🔀 :: [#216] 문의사항 상세보기 페이지 API 연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailComponent.swift
  App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailView.swift
  App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailViewModel.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
  Service/Sources/Data/DataSource/Inquiry/RemoteInquiryDataSourceImpl.swift
  Service/Sources/Domain/InquiryDomain/DTO/Response/FetchInquiryDetailResponseDTO.swift
  Service/Sources/Domain/InquiryDomain/Entity/InquiryDetailEntity.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#220 🔀 :: [#219] 탭 바가 필요없는 View에 탭 바가 생성되는 현상 해결
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
  App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingView.swift
  App/Sources/Feature/ActivityListFeature/ActivityListView.swift
  App/Sources/Feature/CertificationListFeature/Source/Component/CertificationListRow.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailView.swift
  App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
  App/Sources/Feature/EditPostFeature/Source/EditPostView.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityView.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationView.swift
  App/Sources/Feature/InputInquiryFeature/Source/InputInquiryView.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeView.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
  App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailView.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
  App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailView.swift
  App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingView.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
  App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingView.swift
  App/Sources/Feature/PostListFeature/Sources/PostListView.swift
  Service/Sources/Domain/CertificationDomain/DTO/Response/CertificationListResponseDTO.swift
  Service/Sources/Domain/CertificationDomain/Entity/CertificationInfoEntity.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#222 🔀 :: [#221] FAQ 도메인 세팅
  App/Sources/Application/DI/FAQ/AppComponent+FAQ.swift
  Service/Sources/Data/DataSource/FAQ/RemoteFAQDataSourceImpl.swift
  Service/Sources/Data/Repository/FAQ/FAQRepositoryImpl.swift
  Service/Sources/Data/UseCase/FAQ/FetchFAQDetailUseCaseImpl.swift
  Service/Sources/Data/UseCase/FAQ/FetchFAQListUseCaseImpl.swift
  Service/Sources/Data/UseCase/FAQ/InputFAQUseCaseImpl.swift
  Service/Sources/Domain/FAQDomain/API/FAQAPI.swift
  Service/Sources/Domain/FAQDomain/DTO/Request/InputFAQRequestDTO.swift
  Service/Sources/Domain/FAQDomain/DTO/Response/FetchFAQDetailResponseDTO.swift
  Service/Sources/Domain/FAQDomain/DTO/Response/FetchFAQListResponseDTO.swift
  Service/Sources/Domain/FAQDomain/DataSource/RemoteFAQDataSource.swift
  Service/Sources/Domain/FAQDomain/Entity/FAQDetailInfoEntity.swift
  Service/Sources/Domain/FAQDomain/Entity/FAQInfoEntity.swift
  Service/Sources/Domain/FAQDomain/Error/FAQDomainError.swift
  Service/Sources/Domain/FAQDomain/Repository/FAQRepository.swift
  Service/Sources/Domain/FAQDomain/UseCase/FetchFAQDetailUseCase.swift
  Service/Sources/Domain/FAQDomain/UseCase/FetchFAQListUseCase.swift
  Service/Sources/Domain/FAQDomain/UseCase/InputFAQUseCase.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting, ⚡️ Simple, ✨ Feature

#224 🔀 :: [#223] withdraw 도메인 세팅
  App/Sources/Application/DI/Withdraw/AppComponent+Withdraw.swift
  App/Sources/Application/NeedleGenerated.swift
  Service/Sources/Data/DataSource/Withdraw/RemoteWithdrawDataSourceImpl.swift
  Service/Sources/Data/Repository/Withdraw/WithdrawRepositoryImpl.swift
  Service/Sources/Data/UseCase/Withdraw/FetchWithdrawUserListUseCaseImpl.swift
  Service/Sources/Domain/WithdrawDomain/API/WithdrawAPI.swift
  Service/Sources/Domain/WithdrawDomain/DTO/Response/FetchWithdrawUserListResponseDTO.swift
  Service/Sources/Domain/WithdrawDomain/DataSource/RemoteWithdrawDataSource.swift
  Service/Sources/Domain/WithdrawDomain/Entity/WithdrawUserInfoEntity.swift
  Service/Sources/Domain/WithdrawDomain/Error/WithdrawDomainError.swift
  Service/Sources/Domain/WithdrawDomain/Repository/WithdrawRepository.swift
  Service/Sources/Domain/WithdrawDomain/UseCase/FetchWithdrawUserListUseCase.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting, ✨ Feature

#228 🔀 :: [#225] 학생활동목록 페이지 리팩토링
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ActivityListFeature/Model/ActivityListModel.swift
  App/Sources/Feature/ActivityListFeature/Source/ActivityListComponent.swift
  App/Sources/Feature/ActivityListFeature/Source/ActivityListView.swift
  App/Sources/Feature/ActivityListFeature/Source/ActivityListViewModel.swift
  App/Sources/Feature/ActivityListFeature/Source/Component/ActivityListRow.swift
  App/Sources/Feature/ActivityListFeature/ViewModel/ActivityListViewModel.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple

#229 🔀 :: [#225] 학생활동 추가, 수정 페이지 리팩토링
  App/Sources/Application/DI/Activity/AppComponent+Activity.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailComponent.swift
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailViewModel.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityComponent.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityView.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityViewModel.swift
  Service/Sources/Data/DataSource/Activity/RemoteActivityDataSourceImpl.swift
  Service/Sources/Data/Repository/Activity/ActivityRepositoryImpl.swift
  Service/Sources/Data/UseCase/Activity/FetchActivityDetailUseCaseImpl.swift
  Service/Sources/Data/UseCase/Activity/ModifyActibityActivityUseCaseImpl.swift
  Service/Sources/Domain/ActivityDomain/API/ActivityAPI.swift
  Service/Sources/Domain/ActivityDomain/DTO/Response/ActivityDetailResponseDTO.swift
  Service/Sources/Domain/ActivityDomain/DataSource/RemoteActivityDataSource.swift
  Service/Sources/Domain/ActivityDomain/Repository/ActivityRepository.swift
  Service/Sources/Domain/ActivityDomain/UseCase/FetchActivityDetailUseCase.swift
  Service/Sources/Testing/UseCase/FetchActivityDetailUseCaseStub.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple

#234 🔀 :: [#227] Lecture 도메인 수정
  App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/LectureListDetailFeature/Interface/LectureListDetailFactory.swift
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailViewModel.swift
  App/Sources/Feature/LectureListDetailFeature/Source/LectureListDetailComponent.swift
  App/Sources/Feature/LectureListFeature/Component/LectureListRow.swift
  App/Sources/Feature/LectureListFeature/LectureListView.swift
  App/Sources/Feature/LectureListFeature/Model/LectureListModel.swift
  App/Sources/Feature/LectureListFeature/Source/LectureListComponent.swift
  App/Sources/Feature/LectureListFeature/ViewModel/LectureListViewModel.swift
  Service/Sources/Base/Enum/DivisionType.swift
  Service/Sources/Base/Enum/SemesterType.swift
  Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
  Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
  Service/Sources/Data/UseCase/Lecture/ApplyLectureUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/CancelLectureUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/FetchLectureDetailUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/FetchLectureListUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureOpenUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/OpenLectureUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/QueryLectureDetailUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/SearchDepartmentListUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/SearchDivisionListUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/SearchInstructorListUseCaseImpl.swift
  Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
  Service/Sources/Domain/LectureDomain/DTO/Request/LectureOpenRequestDTO.swift
  Service/Sources/Domain/LectureDomain/DTO/Request/OpenLectureRequestDTO.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchDepartmentResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchDivisionListResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchInstructorListResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureDetailResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureListResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
  Service/Sources/Domain/LectureDomain/Entity/DepartmentListEntity.swift
  Service/Sources/Domain/LectureDomain/Entity/DivisionListEntity.swift
  Service/Sources/Domain/LectureDomain/Entity/InstructorListEntity.swift
  Service/Sources/Domain/LectureDomain/Entity/LectureDetailEntity.swift
  Service/Sources/Domain/LectureDomain/Entity/LectureListEntity.swift
  Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
  Service/Sources/Domain/LectureDomain/UseCase/ApplyLectureUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/CancelLectureUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/FetchLectureDetailUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/FetchLectureListUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureApplyUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureCancelUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureOpenUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/OpenLectureUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/QueryLectureDetailUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/QueryLectureListUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/SearchDepartmentListUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/SearchDivisionListUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/SearchInstructorListUseCase.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚙ Setting, ✨ Feature

#230 🔀 :: [#225] 학생활동 상세보기 페이지 리팩토링
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailViewModel.swift
  App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingView.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityViewModel.swift
  Service/Sources/Domain/ActivityDomain/DTO/Response/ActivityDetailResponseDTO.swift
  Service/Sources/Domain/ActivityDomain/Entity/ActivityDetailEntity.swift
  Service/Sources/Testing/UseCase/FetchActivityDetailUseCaseStub.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#232 🔀 :: [#231] 문의사항 답변 작성 페이지 퍼블리싱
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailComponent.swift
  App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailView.swift
  App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailViewModel.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
  App/Sources/Feature/WriteInquiryAnswerFeature /Interface/WriteInquiryAnswerFactory.swift
  App/Sources/Feature/WriteInquiryAnswerFeature /Source/WriteInquiryAnswerComponent.swift
  App/Sources/Feature/WriteInquiryAnswerFeature /Source/WriteInquiryAnswerView.swift
  App/Sources/Feature/WriteInquiryAnswerFeature /Source/WriteInquiryAnswerViewModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#233 🔀 :: [#231] 문의사항 답변 작성 페이지 API 연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/WriteInquiryAnswerFeature /Source/WriteInquiryAnswerComponent.swift
  App/Sources/Feature/WriteInquiryAnswerFeature /Source/WriteInquiryAnswerViewModel.swift
  App/Sources/Feature/WriteInquiryAnswerFeature/Interface/WriteInquiryAnswerFactory.swift
  App/Sources/Feature/WriteInquiryAnswerFeature/Source/WriteInquiryAnswerComponent.swift
  App/Sources/Feature/WriteInquiryAnswerFeature/Source/WriteInquiryAnswerView.swift
  App/Sources/Feature/WriteInquiryAnswerFeature/Source/WriteInquiryAnswerViewModel.swift
  Service/Sources/Data/DataSource/Inquiry/RemoteInquiryDataSourceImpl.swift
  Service/Sources/Data/Repository/Inquiry/InquiryRepositoryImpl.swift
  Service/Sources/Data/UseCase/Inquiry/ReplyInquiryUseCaseImpl.swift
  Service/Sources/Domain/InquiryDomain/API/InquiryAPI.swift
  Service/Sources/Domain/InquiryDomain/DTO/Request/InquiryAnswerRequestDTO.swift
  Service/Sources/Domain/InquiryDomain/DataSource/RemoteInquiryDataSource.swift
  Service/Sources/Domain/InquiryDomain/Repository/InquiryRepository.swift
  Service/Sources/Domain/InquiryDomain/UseCase/ReplyInquiryUseCase.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#236 🔀 :: [#235] 자격증 수정 버튼 클릭 시 페이지 이동 추가
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListView.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListViewModel.swift
  App/Sources/Feature/InputCertificationFeature/Interface/InputCertificationFactory.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationComponent.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationViewModel.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple

#240 🔀 :: [#239] 강의 리스트, 상세보기 페이지 리팩토링
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailViewModel.swift
  App/Sources/Feature/LectureListFeature/LectureListView.swift
  App/Sources/Feature/LectureListFeature/Model/LectureListModel.swift
  App/Sources/Feature/LectureListFeature/Source/Component/LectureListRow.swift
  App/Sources/Feature/LectureListFeature/Source/LectureListComponent.swift
  App/Sources/Feature/LectureListFeature/Source/LectureListView.swift
  App/Sources/Feature/LectureListFeature/Source/LectureListViewModel.swift
  Service/Sources/Base/Enum/LectureStatusType.swift
  Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
  Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
  Service/Sources/Data/UseCase/Lecture/FetchLectureListUseCaseImpl.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureDetailResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureListResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
  Service/Sources/Domain/LectureDomain/Entity/LectureDetailEntity.swift
  Service/Sources/Domain/LectureDomain/Entity/LectureListEntity.swift
  Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
  Service/Sources/Domain/LectureDomain/UseCase/FetchLectureListUseCase.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#238 🔀 :: [#199] AdminUserList 페이지 퍼블리싱
  App/Resources/Icon/Icons.xcassets/magnifyingglass.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/magnifyingglass.imageset/magnifyingglass.svg
  App/Resources/Icon/Icons.xcassets/minus_fill.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/minus_fill.imageset/minus_fill.svg
  App/Resources/Icon/Icons.xcassets/people.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/people.imageset/people.svg
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/AdminRequestUserSignupFeature/Interface/AdminRequestUserSignupFactory.swift
  App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupComponent.swift
  App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupView.swift
  App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupViewModel.swift
  App/Sources/Feature/AdminUserListFeature/Interface/AdminUserListFactory.swift
  App/Sources/Feature/AdminUserListFeature/Source/AdminUserListView.swift
  App/Sources/Feature/AdminUserListFeature/Source/AdminUserListViewModel.swift
  App/Sources/Feature/AdminUserListFeature/Source/Component/AdminUserListComponent.swift
  App/Sources/Feature/AdminUserListFeature/Source/Component/UserNameSearchTextField.swift
  App/Sources/Feature/AdminUserListFeature/Source/Component/UserTypeFilterPopup.swift
  App/Sources/Feature/AdminWithdrawUserListFeature/Interface/AdminWithdrawUserListFactory.swift
  App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListComponent.swift
  App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListView.swift
  App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListViewModel.swift
  App/Sources/Feature/AdminWithdrawUserListFeature/Source/Component/UserCohortFilterPopup.swift
  Service/Sources/Base/Enum/UserAuthorityType.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#242 🔀 :: [#237] 마이페이지 API 연결
  App/Sources/Application/DI/User/AppComponent+User.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageComponent.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageView.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageViewModel.swift
  Service/Sources/Data/DataSource/Auth/RemoteDataSourceImpl.swift
  Service/Sources/Data/DataSource/User/RemoteUserDataSourceImpl.swift
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/Repository/User/UserRepositoryImpl.swift
  Service/Sources/Data/UseCase/User/FetchMyInfoUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/UserDomain/API/UserAPI.swift
  Service/Sources/Domain/UserDomain/DTO/Response/FetchMyInfoResponseDTO.swift
  Service/Sources/Domain/UserDomain/DataSource/RemoteUserDataSource.swift
  Service/Sources/Domain/UserDomain/Repository/UserRepository.swift
  Service/Sources/Domain/UserDomain/UseCase/FetchMyInfoUseCase.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#243 🔀 :: [#241] 비밀번호 변경 페이지 퍼블리싱
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ChangePasswordFeature/Interface/ChangePasswordFactory.swift
  App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordComponent.swift
  App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordView.swift
  App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordViewModel.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageComponent.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageView.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageViewModel.swift
Labels: 0️⃣ Priority: Critical

#244 🔀 :: [#241] 비밀번호 변경 페이지 API 연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordComponent.swift
  App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordView.swift
  App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordViewModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#245 🔀 :: [#241] 로그인 성공 페이지 퍼블리싱
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordComponent.swift
  App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordView.swift
  App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordViewModel.swift
  App/Sources/Feature/SuccessChangePasswordFeature/Interface/SuccessChangePasswordFactory.swift
  App/Sources/Feature/SuccessChangePasswordFeature/Source/SuccessChangePasswordComponent.swift
  App/Sources/Feature/SuccessChangePasswordFeature/Source/SuccessChangePasswordView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#247 🔀 :: [#246] 어드민 - 사용자 명단 페이지 API 연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/AdminUserListFeature/Source/AdminUserListComponent.swift
  App/Sources/Feature/AdminUserListFeature/Source/AdminUserListView.swift
  App/Sources/Feature/AdminUserListFeature/Source/AdminUserListViewModel.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageComponent.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageView.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageViewModel.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#248 🔀 :: [#246] 어드민 - 가입 요청자 명단 페이지 API 연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupComponent.swift
  App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupView.swift
  App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupViewModel.swift
  App/Sources/Feature/AdminUserListFeature/Source/AdminUserListView.swift
  Service/Sources/Data/DataSource/Admin/RemoteAdminDataSourceImpl.swift
  Service/Sources/Data/Repository/Admin/AdminRespositoryImpl.swift
  Service/Sources/Data/UseCase/Admin/ApproveUserSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Admin/RejectUserSignupUseCaseImpl.swift
  Service/Sources/Data/UseCase/Admin/WithdrawUserUseCaseImpl.swift
  Service/Sources/Domain/AdminDomain/API/AdminAPI.swift
  Service/Sources/Domain/AdminDomain/DataSource/RemoteAdminDataSource.swift
  Service/Sources/Domain/AdminDomain/Repository/AdminRepository.swift
  Service/Sources/Domain/AdminDomain/UseCase/ApproveUserSignupUseCase.swift
  Service/Sources/Domain/AdminDomain/UseCase/RejectUserSignupUseCase.swift
  Service/Sources/Domain/AdminDomain/UseCase/WithdrawUserSignupUseCase.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#249 🔀 :: [#246] 어드민 - 탈퇴 예정자 명단 페이지 API 연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListComponent.swift
  App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListView.swift
  App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListViewModel.swift
  App/Sources/Feature/AdminWithdrawUserListFeature/Source/Component/UserCohortFilterPopup.swift
  Service/Sources/Domain/AdminDomain/API/AdminAPI.swift
  Service/Sources/Domain/WithdrawDomain/DTO/Response/FetchWithdrawUserListResponseDTO.swift
  Service/Sources/Domain/WithdrawDomain/Entity/WithdrawUserInfoEntity.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#251 🔀 :: [#250] Email 도메인 세팅
  App/Sources/Application/DI/Email/AppComponent+Email.swift
  App/Sources/Feature/SuccessChangePasswordFeature/Source/SuccessChangePasswordView.swift
  Service/Sources/Base/BitgouelAPI.swift
  Service/Sources/Data/DataSource/Email/RemoteEmailDataSourceImpl.swift
  Service/Sources/Data/Repository/Email/EmailRepositoryImpl.swift
  Service/Sources/Data/UseCase/Email/FetchEmailVerificationStatusUseCaseImpl.swift
  Service/Sources/Data/UseCase/Email/SendEmailCertificationLinkUseCaseImpl.swift
  Service/Sources/Domain/EmailDomain/API/EmailAPI.swift
  Service/Sources/Domain/EmailDomain/DTO/FetchEmailVerificationStatusResponseDTO.swift
  Service/Sources/Domain/EmailDomain/DataSource/RemoteEmailDataSource.swift
  Service/Sources/Domain/EmailDomain/Entity/EmailVerificationStatusEntity.swift
  Service/Sources/Domain/EmailDomain/Repository/EmailRepository.swift
  Service/Sources/Domain/EmailDomain/UseCase/FetchEmailVertificationStatusUseCase.swift
  Service/Sources/Domain/EmailDomain/UseCase/SendEmailCertificationLinkUseCase.swift
Labels: 0️⃣ Priority: Critical, ⚙ Setting, ✨ Feature

#253 🔀 :: [#252] 비밀번호 찾기 - 이메일 인증페이지 퍼블리싱
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/TextField/SecureBitgoeulTextField.swift
  App/Sources/Feature/FindPasswordFeature/Interface/FindPasswordFactory.swift
  App/Sources/Feature/FindPasswordFeature/Source/FindPasswordComponent.swift
  App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
  App/Sources/Feature/FindPasswordFeature/Source/FindPasswordViewModel.swift
  App/Sources/Feature/FindPasswordFeature/Source/View/SendEmailView.swift
  App/Sources/Feature/LoginFeature/Sources/LoginComponent.swift
  App/Sources/Feature/LoginFeature/Sources/LoginView.swift
  App/Sources/Feature/LoginFeature/Sources/LoginViewModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#254 🔀 :: [#252] 비밀번호 찾기 - 이메일 인증 페이지 API 연결
  App/Sources/Application/DI/Auth/AppComponent+Auth.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/FindPasswordFeature/Source/FindPasswordComponent.swift
  App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
  App/Sources/Feature/FindPasswordFeature/Source/FindPasswordViewModel.swift
  Service/Sources/Data/DataSource/Auth/RemoteDataSourceImpl.swift
  Service/Sources/Data/DataSource/Email/RemoteEmailDataSourceImpl.swift
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/Repository/Email/EmailRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/FindPasswordUseCaseImpl.swift
  Service/Sources/Data/UseCase/Email/SendEmailCertificationLinkUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/AuthDomain/UseCase/FindPasswordUseCase.swift
  Service/Sources/Domain/EmailDomain/API/EmailAPI.swift
  Service/Sources/Domain/EmailDomain/DTO/EmailRequestDTO.swift
  Service/Sources/Domain/EmailDomain/DataSource/RemoteEmailDataSource.swift
  Service/Sources/Domain/EmailDomain/Repository/EmailRepository.swift
  Service/Sources/Domain/EmailDomain/UseCase/SendEmailCertificationLinkUseCase.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#255 🔀 :: [#252] 비밀번호 찾기 - 비밀번호 변경 페이지 퍼블리싱
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/DI/Email/AppComponent+Email.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/BaseFeature/Flow/SceneFlow.swift
  App/Sources/Feature/FindPasswordFeature/Source/FindPasswordComponent.swift
  App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
  App/Sources/Feature/FindPasswordFeature/Source/FindPasswordViewModel.swift
  App/Sources/Feature/FindPasswordFeature/Source/View/SendEmailView.swift
  App/Sources/Feature/LoginFeature/Sources/LoginView.swift
  App/Sources/Feature/NewPasswordFeature/Interface/NewPasswordFactory.swift
  App/Sources/Feature/NewPasswordFeature/Source/NewPasswordComponent.swift
  App/Sources/Feature/NewPasswordFeature/Source/NewPasswordView.swift
  App/Sources/Feature/NewPasswordFeature/Source/NewPasswordViewModel.swift
  App/Sources/Feature/NewPasswordFeature/Source/View/SuccessFindPasswordView.swift
  App/Sources/Feature/RootFeature/RootComponent.swift
  App/Sources/Feature/RootFeature/RootView.swift
  Service/Sources/Data/DataSource/Email/RemoteEmailDataSourceImpl.swift
  Service/Sources/Data/Repository/Email/EmailRepositoryImpl.swift
  Service/Sources/Data/UseCase/Email/FetchEmailVerificationStatusUseCaseImpl.swift
  Service/Sources/Domain/EmailDomain/DTO/FetchEmailVerificationStatusResponseDTO.swift
  Service/Sources/Domain/EmailDomain/DataSource/RemoteEmailDataSource.swift
  Service/Sources/Domain/EmailDomain/Entity/EmailVerificationStatusEntity.swift
  Service/Sources/Domain/EmailDomain/Repository/EmailRepository.swift
  Service/Sources/Domain/EmailDomain/UseCase/FetchEmailVertificationStatusUseCase.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#256 🔀 :: [#252] 비밀번호 찾기 - 비밀변호 변경 기능 추가
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
  App/Sources/Feature/NewPasswordFeature/Interface/NewPasswordFactory.swift
  App/Sources/Feature/NewPasswordFeature/Source/NewPasswordComponent.swift
  App/Sources/Feature/NewPasswordFeature/Source/NewPasswordView.swift
  App/Sources/Feature/NewPasswordFeature/Source/NewPasswordViewModel.swift
  Service/Sources/Data/DataSource/Auth/RemoteDataSourceImpl.swift
  Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
  Service/Sources/Data/UseCase/Auth/FindPasswordUseCaseImpl.swift
  Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
  Service/Sources/Domain/AuthDomain/DTO/Request/FindPasswordRequestDTO.swift
  Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
  Service/Sources/Domain/AuthDomain/UseCase/FindPasswordUseCase.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#258 🔀 :: [#257] 강의 목록 페이지 디자인 변경사항 적용
  App/Sources/Feature/LectureListFeature/Source/Component/LectureListRow.swift
  App/Sources/Feature/LectureListFeature/Source/LectureListView.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple

#261 🔀 :: [#260] FAQ Domain 변경사항 적용
  App/Sources/Application/DI/FAQ/AppComponent+FAQ.swift
  Service/Sources/Data/DataSource/FAQ/RemoteFAQDataSourceImpl.swift
  Service/Sources/Data/Repository/FAQ/FAQRepositoryImpl.swift
  Service/Sources/Data/UseCase/FAQ/FetchFAQDetailUseCaseImpl.swift
  Service/Sources/Domain/FAQDomain/API/FAQAPI.swift
  Service/Sources/Domain/FAQDomain/DTO/Response/FetchFAQDetailResponseDTO.swift
  Service/Sources/Domain/FAQDomain/DTO/Response/FetchFAQListResponseDTO.swift
  Service/Sources/Domain/FAQDomain/DataSource/RemoteFAQDataSource.swift
  Service/Sources/Domain/FAQDomain/Entity/FAQDetailInfoEntity.swift
  Service/Sources/Domain/FAQDomain/Entity/FAQInfoEntity.swift
  Service/Sources/Domain/FAQDomain/Repository/FAQRepository.swift
  Service/Sources/Domain/FAQDomain/UseCase/FetchFAQDetailUseCase.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple

#263 🔀 :: [#262] FAQ 페이지 퍼블리싱
  App/Sources/Feature/MainFeature/Source/ClubRoleView.swift
  App/Sources/Feature/MainFeature/Source/GovernmentView.swift
  App/Sources/Feature/MainFeature/Source/IntroduceView.swift
  App/Sources/Feature/MainFeature/Source/JobDetailView.swift
  App/Sources/Feature/MainFeature/Source/MainView.swift
  App/Sources/Feature/MainFeature/Source/TabView/Club/AiFusionAndCompositeClubView.swift
  App/Sources/Feature/MainFeature/Source/TabView/Club/CultureIndustryClubView.swift
  App/Sources/Feature/MainFeature/Source/TabView/Club/EnergyIndustryClubView.swift
  App/Sources/Feature/MainFeature/Source/TabView/Club/FutureTransportClubView.swift
  App/Sources/Feature/MainFeature/Source/TabView/Club/MedicalHealthClubView.swift
  App/Sources/Feature/MainFeature/Source/TabView/ClubsAndCompanysNameView.swift
  App/Sources/Feature/MainFeature/Source/TabView/Company/AiFusionAndCompositeCompanyView.swift
  App/Sources/Feature/MainFeature/Source/TabView/Company/CultureIndustryCompanyView.swift
  App/Sources/Feature/MainFeature/Source/TabView/Company/EnergyIndustryCompanyView.swift
  App/Sources/Feature/MainFeature/Source/TabView/Company/FutureTransportCompanyView.swift
  App/Sources/Feature/MainFeature/Source/TabView/Company/MedicalHealthCompanyView.swift
  App/Sources/Feature/MainFeature/Source/UniversityView.swift
  App/Sources/Feature/MainFeature/Source/View/BitgouelPromotionView.swift
  App/Sources/Feature/MainFeature/Source/View/ClubPromotionView.swift
  App/Sources/Feature/MainFeature/Source/View/FAQView.swift
  App/Sources/Feature/MainFeature/Source/View/GovernmentView.swift
  App/Sources/Feature/MainFeature/Source/View/HighSchoolPromotionView.swift
  App/Sources/Feature/MainFeature/Source/View/UniversityView.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple

#264 🔀 :: [#262] 메인페이지 - FAQ API 연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/MainFeature/Source/MainComponent.swift
  App/Sources/Feature/MainFeature/Source/MainView.swift
  App/Sources/Feature/MainFeature/Source/MainViewModel.swift
  App/Sources/Feature/MainFeature/Source/View/FAQView.swift
  App/Sources/Feature/MainFeature/Source/View/InputFAQView.swift
  Service/Sources/Domain/FAQDomain/DTO/Response/FetchFAQListResponseDTO.swift
  Service/Sources/Domain/FAQDomain/Entity/FAQInfoEntity.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#269 🔀 :: [#265] 게스트 로그인 구현
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/Alert/LoginAlert.swift
  App/Sources/Feature/ClubListFeature/Source/ClubListComponent.swift
  App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
  App/Sources/Feature/ClubListFeature/Source/ClubListViewModel.swift
  App/Sources/Feature/ClubListFeature/Source/Interface/ClubListFactory.swift
  App/Sources/Feature/LectureListFeature/Interface/LectureListFactory.swift
  App/Sources/Feature/LectureListFeature/Source/LectureListComponent.swift
  App/Sources/Feature/LectureListFeature/Source/LectureListView.swift
  App/Sources/Feature/LectureListFeature/Source/LectureListViewModel.swift
  App/Sources/Feature/LoginFeature/Sources/LoginView.swift
  App/Sources/Feature/MainFeature/Source/MainView.swift
  App/Sources/Feature/MainTabFeature/Source/MainTabView.swift
  App/Sources/Feature/MyPageFeature/Interface/MyPageFactory.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageComponent.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageView.swift
  App/Sources/Feature/MyPageFeature/Source/MyPageViewModel.swift
  App/Sources/Feature/PostListFeature/Interface/PostListFactory.swift
  App/Sources/Feature/PostListFeature/Sources/PostListComponent.swift
  App/Sources/Feature/PostListFeature/Sources/PostListView.swift
  App/Sources/Feature/PostListFeature/Sources/PostListViewModel.swift
  App/Sources/Feature/SignUpFeature/SignUpView.swift
  App/Sources/Feature/SignUpFeature/SignUpViewModel.swift
  Service/Sources/Base/Enum/CareerClubType.swift
  Service/Sources/Base/Enum/HighSchoolType.swift
  Service/Sources/Data/DataSource/Auth/LocalAuthDataSourceImpl.swift
  Service/Sources/Data/UseCase/Certification/QueryCertificationListByStudentUseCaseImpl.swift
  Service/Sources/Data/UseCase/Certification/QueryCertificationListByTeacherUseCaseImpl.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#271 🔀 :: [#270] dismiss Action 추가
  App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple

#273 🔀 :: [#272] ButtonPadding 수정
  App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupView.swift
  App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListView.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple

#275 🔀 :: [#274] hideKeyboard 추가
  App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordView.swift
  App/Sources/Feature/LoginFeature/Sources/LoginView.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple

#277 🔀 :: [#276] ScrollView 추가
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ActivityListFeature/Source/Component/ActivityListRow.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListViewModel.swift
  App/Sources/Feature/EditPostFeature/Interface/EditPostFactory.swift
  App/Sources/Feature/EditPostFeature/Source/EditPostComponent.swift
  App/Sources/Feature/EditPostFeature/Source/EditPostView.swift
  App/Sources/Feature/EditPostFeature/Source/EditPostViewModel.swift
  App/Sources/Feature/InputInquiryFeature/Source/InputInquiryView.swift
  App/Sources/Feature/InputNoticeFeature/Source/InputNoticeView.swift
  App/Sources/Feature/InputPostFeature/Interface/InputPostFactory.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostComponent.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostViewModel.swift
  App/Sources/Feature/MainTabFeature/Source/MainTabView.swift
  App/Sources/Feature/NewPasswordFeature/Source/NewPasswordView.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailComponent.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailViewModel.swift
  App/Sources/Feature/PostListFeature/Sources/PostListView.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️ Simple
