Repository School-of-Company/Bitgouel-iOS, pull requests merged in 2024-01, with the labels that each got.

#117 🔀 :: [#79] 학생 회원가입 로직에 공통 회원가입 로직 추가
  App/Sources/Feature/StudentSignUpFeature/StudentSignUpView.swift
  App/Sources/Feature/StudentSignUpFeature/StudentSignUpViewModel.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor

#119 🔀 :: [#79] 학생회원가입 검증 로직 리팩토링
  App/Sources/Feature/StudentSignUpFeature/StudentSignUpView.swift
  App/Sources/Feature/StudentSignUpFeature/StudentSignUpViewModel.swift
  App/Sources/Feature/StudentSignUpFeature/View/SchoolListRowView.swift
  App/Sources/Feature/StudentSignUpFeature/View/SchoolListView.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor

#116 🔀 :: [#102] 학생활동 추가 페이지 퍼블리싱
  App/Resources/Icon/Icons.xcassets/setting.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/setting.imageset/setting.svg
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/Extensions/View+hideKeyBoard.swift
  App/Sources/Feature/ActivityListFeature/ActivityListView.swift
  App/Sources/Feature/ActivityListFeature/Source/ActivityListComponent.swift
  App/Sources/Feature/ActivityListFeature/ViewModel/ActivityListViewModel.swift
  App/Sources/Feature/InputActivityFeature/Interface/InputActivityFactory.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityComponent.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityView.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityViewModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#125 🔀 :: [#124] UserDomain API 세팅
  App/Sources/Application/DI/User/AppComponent+User.swift
  App/Sources/Application/NeedleGenerated.swift
  Service/Sources/Data/DataSource/User/RemoteUserDataSourceImpl.swift
  Service/Sources/Data/Repository/User/UserRepositoryImpl.swift
  Service/Sources/Data/UseCase/User/ChangePasswordUseCaseImpl.swift
  Service/Sources/Data/UseCase/User/QueryMyInfoUseCaseImpl.swift
  Service/Sources/Domain/UserDomain/API/UserAPI.swift
  Service/Sources/Domain/UserDomain/DTO/Request/ChangePasswordRequestDTO.swift
  Service/Sources/Domain/UserDomain/DTO/Response/InquiryMyInfoResponseDTO.swift
  Service/Sources/Domain/UserDomain/DataSource/RemoteUserDataSource.swift
  Service/Sources/Domain/UserDomain/Entity/MyInfoEntity.swift
  Service/Sources/Domain/UserDomain/Error/UserDomainError.swift
  Service/Sources/Domain/UserDomain/Repository/UserRepository.swift
  Service/Sources/Domain/UserDomain/UseCase/ChangePasswordUseCase.swift
  Service/Sources/Domain/UserDomain/UseCase/QueryMyInfoUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#122 🔀 :: [#103] 학생활동 세부설정 기능 추가
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ActivityDetailSettingFeature/Interface/ActivityDetailSettingFactory.swift
  App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingComponent.swift
  App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingView.swift
  App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingViewModel.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityComponent.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityView.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityViewModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#135 🔀 :: [#134] AppComponent+Lecture 추가
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
  App/Sources/Application/DI/User/AppComponent+User.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingComponent.swift
  App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingViewModel.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityView.swift
  App/Sources/Feature/InputActivityFeature/Source/InputActivityViewModel.swift
  Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
  Service/Sources/Data/DataSource/User/RemoteUserDataSourceImpl.swift
  Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
  Service/Sources/Data/Repository/User/UserRepositoryImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureApplyUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureDetailInquiryUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureListInquirtyUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureOpenUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/WaitingLectureApproveUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/WaitingLectureRejectUseCaseImpl.swift
  Service/Sources/Data/UseCase/User/ChangePasswordUseCaseImpl.swift
  Service/Sources/Data/UseCase/User/QueryMyInfoUseCaseImpl.swift
  Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
  Service/Sources/Domain/LectureDomain/UseCase/WaitingLectureUseCase.swift
  Service/Sources/Domain/UserDomain/API/UserAPI.swift
  Service/Sources/Domain/UserDomain/DTO/Request/ChangePasswordRequestDTO.swift
  Service/Sources/Domain/UserDomain/DTO/Response/InquiryMyInfoResponseDTO.swift
  Service/Sources/Domain/UserDomain/Entity/MyInfoEntity.swift
  Service/Sources/Domain/UserDomain/Error/UserDomainError.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature
