Repository School-of-Company/Bitgouel-iOS, pull requests merged in 2024-02, with the labels that each got.

#140 🔀 :: [#133] 동아리 - 동아리 목록 페이지 EmptyContent 퍼블리싱
  App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
  App/Sources/Feature/ClubListFeature/Source/Component/ClubListEmptyContentView.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#118 🔀 :: [#104] 학생활동 상세 페이지 퍼블리싱
  App/Sources/Application/DI/Activity/AppComponent+Activity.swift
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ActivityDetailFeature/Interface/ActivityDetailFactory.swift
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailComponent.swift
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailViewModel.swift
  App/Sources/Feature/ActivityListFeature/ActivityListView.swift
  App/Sources/Feature/ActivityListFeature/Component/StudentActivityRow.swift
  App/Sources/Feature/ActivityListFeature/Interface/ActivityListFactory.swift
  App/Sources/Feature/ActivityListFeature/Model/ActivityListModel.swift
  App/Sources/Feature/ActivityListFeature/Source/ActivityListComponent.swift
  App/Sources/Feature/ActivityListFeature/ViewModel/ActivityListViewModel.swift
  Service/Sources/Data/DataSource/Activity/RemoteActivityDataSourceImpl.swift
  Service/Sources/Data/DataSource/Auth/LocalAuthDataSourceImpl.swift
  Service/Sources/Data/Repository/Activity/ActivityRepositoryImpl.swift
  Service/Sources/Data/UseCase/Activity/ApproveStudentActivityUseCaseImpl.swift
  Service/Sources/Data/UseCase/Activity/DeleteStudentActivityUseCaseImpl.swift
  Service/Sources/Data/UseCase/Activity/QueryStudentActivityDetailsUseCaseImpl.swift
  Service/Sources/Data/UseCase/Activity/RejectStudentActivityUseCaseImpl.swift
  Service/Sources/Data/UseCase/Activity/UpdateStudentActivityUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/LoadUserAuthorityUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/LoginUseCaseImpl.swift
  Service/Sources/Data/UseCase/Auth/SaveUserAuthorityUseCaseImpl.swift
  Service/Sources/Domain/ActivityDomain/API/ActivityAPI.swift
  Service/Sources/Domain/ActivityDomain/DTO/Response/ActivitiesResponseDTO.swift
  Service/Sources/Domain/ActivityDomain/DTO/Response/StudentActivityDetailResponseDTO.swift
  Service/Sources/Domain/ActivityDomain/DataSource/RemoteActivityDataSource.swift
  Service/Sources/Domain/ActivityDomain/Entity/ActivityEntity.swift
  Service/Sources/Domain/ActivityDomain/Entity/StudentActivityDetailEntity.swift
  Service/Sources/Domain/ActivityDomain/Repository/ActivityRepository.swift
  Service/Sources/Domain/ActivityDomain/UseCase/ApproveStudentActivityUseCase.swift
  Service/Sources/Domain/ActivityDomain/UseCase/DeleteStudentActivityUseCase.swift
  Service/Sources/Domain/ActivityDomain/UseCase/QueryStudentActivityDetailsUseCase.swift
  Service/Sources/Domain/ActivityDomain/UseCase/RejectStudentActivityUseCase.swift
  Service/Sources/Domain/ActivityDomain/UseCase/UpdateStudentActibityUseCase.swift
  Service/Sources/Domain/ClubDomain/DTO/Response/StudentListByClubResponseDTO.swift
  Service/Sources/Domain/ClubDomain/Entity/SingleStudentEntity.swift
  Service/Sources/Testing/UseCase/QueryActivityDetailUseCaseStub.swift
  Service/Sources/Testing/UseCase/QueryMyStudentActivityUseCaseStub.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#126 🔀 :: [#123] 마이페이지 퍼블리싱
  App/Sources/Feature/ActivityListFeature/ActivityListView.swift
  App/Sources/Feature/MyPageFeature/MyPageView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#145 🔀 :: [136] 강의 목록 페이지 API 연결
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/LectureListDetailFeature/Interface/LectureListDetailFactory.swift
  App/Sources/Feature/LectureListDetailFeature/Source/LectureListDetailComponent.swift
  App/Sources/Feature/LectureListFeature/Component/LectureListRow.swift
  App/Sources/Feature/LectureListFeature/Interface/LectureListFactory.swift
  App/Sources/Feature/LectureListFeature/LectureListView.swift
  App/Sources/Feature/LectureListFeature/LectureListViewModel.swift
  App/Sources/Feature/LectureListFeature/Model/LectureListModel.swift
  App/Sources/Feature/LectureListFeature/Source/LectureListComponent.swift
  App/Sources/Feature/LectureListFeature/ViewModel/LectureListViewModel.swift
  Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
  Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureDetailInquiryUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureListInquirtyUseCaseImpl.swift
  Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureListResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
  Service/Sources/Domain/LectureDomain/Entity/LectureListEntity.swift
  Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureDetailInquiryUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureListInquirtyUseCase.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#130 🔀 :: [#129] 게시글 - 게시글 목록 페이지 퍼블리싱
  App/Resources/Icon/Icons.xcassets/Image.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/Image.imageset/Frame 7407.svg
  App/Resources/Icon/Icons.xcassets/vertical_ellipsis_fill.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/vertical_ellipsis_fill.imageset/Frame 7407.svg
  App/Sources/Feature/PostListFeature/Sources/Component/PostListRow.swift
  App/Sources/Feature/PostListFeature/Sources/PostListView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#149 🔀 :: [#148] Token 저장 오류 해결
  Service/Sources/Base/API/RefreshAPI.swift
  Service/Sources/Base/DataSource/BaseRemoteDataSource.swift
  Service/Sources/Base/Plugins/Jwt/JwtAuthorizable.swift
  Service/Sources/Base/Plugins/Jwt/JwtPlugin.swift
  Service/Sources/Keychain/Sources/KeychainImpl.swift
  Service/Sources/Utils/Date/DateUtil.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ✨ Feature, 🐞 Bug

#147 🔀 :: [#144] 동아리 - 동아리 상세조회 API 연결
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ClubDetailFaeture/Interface/ClubDetailFactory.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailComponent.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailView.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailViewModel.swift
  Service/Sources/Testing/UseCase/QueryClubDetailUseCaseStub.swift
  Service/Sources/Testing/UseCase/QueryStudentListByClubUseCaseStub.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#132 🔀 :: [#131] 게시글 - 게시글 세부 설정 페이지 퍼블리싱
  App/Sources/DesignSystem/TextField/BitgoeulTextField.swift
  App/Sources/Feature/PostDetailSettingFeature/Interface/PostDetailSettingFactory.swift
  App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingComponent.swift
  App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingView.swift
  App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingViewModel.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#156 🔀 :: [#150] DesignSystem DetailView 추가
  App/Sources/DesignSystem/View/DetailView.swift
  App/Sources/DesignSystem/View/InputFormView.swift
  App/Sources/DesignSystem/View/LinkDetailSettingView.swift
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️ Simple

#154 🔀 :: [#150] DesignSystem LinkDetailSettingView 추가
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/BottomSheet/AlterBottomSheet.swift
  App/Sources/DesignSystem/TextField/BitgoeulTextField.swift
  App/Sources/DesignSystem/View/DetailView.swift
  App/Sources/DesignSystem/View/InputFormView.swift
  App/Sources/DesignSystem/View/LinkDetailSettingView.swift
  App/Sources/DesignSystem/View/Row/ListRow.swift
  App/Sources/DesignSystem/View/Row/RoundListRow.swift
  App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
  App/Sources/Feature/PostDetailSettingFeature/Interface/PostDetailSettingFactory.swift
  App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingComponent.swift
  App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingView.swift
  App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingViewModel.swift
  App/Sources/Feature/PostListFeature/Sources/PostListView.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️ Simple

#158 🔀 :: [#157] LectureDomain 수정
  App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/LectureListFeature/Component/LectureListRow.swift
  App/Sources/Feature/LectureListFeature/LectureListView.swift
  App/Sources/Feature/LectureListFeature/ViewModel/LectureListViewModel.swift
  Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
  Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureCancleUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/WaitingLectureRejectUseCaseImpl.swift
  Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureListResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
  Service/Sources/Domain/LectureDomain/Entity/LectureListEntity.swift
  Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureCancleUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/WaitingLectureRejectUseCase.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️ Simple

#160 🔀 :: [#159] 게시글 - 게시글 목록 페이지 API 연결
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/BottomSheet/AlterBottomSheet.swift
  App/Sources/DesignSystem/View/Row/ListRow.swift
  App/Sources/Feature/InputPostFeature/Interface/InputPostFactory.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostComponent.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
  App/Sources/Feature/InquiryListFeature/Interface/InquiryListFactory.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListComponent.swift
  App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
  App/Sources/Feature/NoticeListFeature/Interface/NoticeListFactory.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListComponent.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
  App/Sources/Feature/PostDetailFeature/Interface/PostDetailFactory.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailComponent.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
  App/Sources/Feature/PostListFeature/Sources/PostListComponent.swift
  App/Sources/Feature/PostListFeature/Sources/PostListView.swift
  App/Sources/Feature/PostListFeature/Sources/PostListViewModel.swift
  App/Sources/Presentation/RemoveMe5.swift
  Service/Sources/Data/DataSource/Post/RemotePostDataSourceImpl.swift
  Service/Sources/Data/Repository/Post/PostRepositoryImpl.swift
  Service/Sources/Data/UseCase/Post/QueryPostListUseCaseImpl.swift
  Service/Sources/Domain/ActivityDomain/Entity/ActivitiesEntity.swift
  Service/Sources/Domain/PostDomain/API/PostAPI.swift
  Service/Sources/Domain/PostDomain/DTO/Response/PostsResponseDTO.swift
  Service/Sources/Domain/PostDomain/DataSource/RemotePostDataSource.swift
  Service/Sources/Domain/PostDomain/Entity/PostEntity.swift
  Service/Sources/Domain/PostDomain/Repository/PostRepository.swift
  Service/Sources/Domain/PostDomain/UseCase/QueryPostListUseCase.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#164 🔀 :: 게시글 - 게시글 추가 API연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostComponent.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostViewModel.swift
  Service/Sources/Domain/PostDomain/DTO/Request/InputPostRequestDTO.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#161 🔀 :: [#146] 강의 상세 보기 페이지 API 연결
  App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/Button/BitgouelButton/BitgouelButtonStyle.swift
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
  App/Sources/Feature/LectureListDetailFeature/LectureListDetailViewModel.swift
  App/Sources/Feature/LectureListDetailFeature/Source/LectureListDetailComponent.swift
  Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
  Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
  Service/Sources/Data/UseCase/Lecture/LectureCancelUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/QueryLectureDetailUseCaseImpl.swift
  Service/Sources/Data/UseCase/Lecture/QueryLectureListUseCaseImpl.swift
  Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
  Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureDeailResponseDTO.swift
  Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
  Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureCancelUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/LectureDetailInquiryUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/QueryLectureDetailUseCase.swift
  Service/Sources/Domain/LectureDomain/UseCase/QueryLectureListUseCase.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#167 🔀 :: 게시글 - 게시글 상세보기 페이지 API 연결
  App/Sources/Application/DI/Post/AppComponent+Post.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/View/DetailView.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailComponent.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailViewModel.swift
  App/Sources/Feature/PostListFeature/Sources/PostListView.swift
  App/Sources/Feature/PostListFeature/Sources/PostListViewModel.swift
  Service/Sources/Domain/PostDomain/API/PostAPI.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#166 🔀 :: [#165] 게시글 - 게시글 상세보기 페이지 퍼블리싱
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/DI/Post/AppComponent+Post.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/View/DetailView.swift
  App/Sources/Feature/EditPostFeature/Interface/EditPostFactory.swift
  App/Sources/Feature/EditPostFeature/Source/EditPostComponent.swift
  App/Sources/Feature/EditPostFeature/Source/EditPostView.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
  App/Sources/Feature/PostDetailFeature/Interface/PostDetailFactory.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailComponent.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailViewModel.swift
  App/Sources/Feature/PostListFeature/Sources/PostListView.swift
  App/Sources/Feature/PostListFeature/Sources/PostListViewModel.swift
  Service/Sources/Domain/PostDomain/API/PostAPI.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#174 🔀 :: [#171] 회원가입 성공 후 성공화면 띄우기
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/CommonSignUpFeature/CommonSignUpView.swift
  App/Sources/Feature/CommonSignUpFeature/CommonSignUpViewModel.swift
  App/Sources/Feature/LoginFeature/Sources/LoginComponent.swift
  App/Sources/Feature/LoginFeature/Sources/LoginView.swift
  App/Sources/Feature/SignUpFeature/Interface/SignUpFactory.swift
  App/Sources/Feature/SignUpFeature/SignUpComponent.swift
  App/Sources/Feature/SignUpFeature/SignUpView.swift
  App/Sources/Feature/SignUpFeature/SignUpViewModel.swift
  App/Sources/Feature/SignUpFeature/View/SchoolListRowView.swift
  App/Sources/Feature/SignUpFeature/View/SchoolListView.swift
  App/Sources/Feature/SignUpFeature/View/SearchClubListRowView.swift
  App/Sources/Feature/SignUpFeature/View/SearchClubListView.swift
  App/Sources/SuccessSignUpFeature/Interface/SuccessSignUpFactory.swift
  App/Sources/SuccessSignUpFeature/Sources/SuccessSignUpComponent.swift
  App/Sources/SuccessSignUpFeature/SuccessSignUpView.swift
Labels: 1️⃣ Priority: High, ✨ Feature, 🐞 Bug

#179 🔀 :: [#178] 동아리 목록 페이지 API 연결
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/ClubDetailFaeture/Interface/ClubDetailFactory.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailComponent.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailView.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailViewModel.swift
  App/Sources/Feature/ClubListFeature/Source/ClubListComponent.swift
  App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
  App/Sources/Feature/ClubListFeature/Source/ClubListViewModel.swift
  App/Sources/Feature/ClubListFeature/Source/Component/ClubListEmptyContentView.swift
  App/Sources/Feature/ClubListFeature/Source/Component/ClubListRow.swift
  Service/Sources/Data/DataSource/Club/RemoteClubDataSourceImpl.swift
  Service/Sources/Data/Repository/Club/ClubRepositoryImpl.swift
  Service/Sources/Data/UseCase/Club/QueryClubDatailUseCaseImpl.swift
  Service/Sources/Data/UseCase/Club/QueryClubListUseCaseImpl.swift
  Service/Sources/Data/UseCase/Club/QueryStudentDetailByClubUseCaseImpl.swift
  Service/Sources/Domain/ClubDomain/API/ClubAPI.swift
  Service/Sources/Domain/ClubDomain/DTO/Response/ClubDetailResponseDTO.swift
  Service/Sources/Domain/ClubDomain/DTO/Response/ClubListResponseDTO.swift
  Service/Sources/Domain/ClubDomain/DataSource/RemoteClubDataSource.swift
  Service/Sources/Domain/ClubDomain/Entity/ClubDetailEntity.swift
  Service/Sources/Domain/ClubDomain/Entity/ClubEntity.swift
  Service/Sources/Domain/ClubDomain/Repository/ClubRepository.swift
  Service/Sources/Domain/ClubDomain/UseCase/QueryClubDetailUseCase.swift
  Service/Sources/Domain/ClubDomain/UseCase/QueryClubListUseCase.swift
  Service/Sources/Domain/ClubDomain/UseCase/QueryStudentDetailByClubUseCase.swift
  Service/Sources/Testing/UseCase/QueryClubDetailUseCaseStub.swift
  Service/Sources/Testing/UseCase/QueryStudentListByClubUseCaseStub.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#183 🔀 :: 게시글 수정 페이지 API 연결
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/View/DetailView.swift
  App/Sources/Feature/EditPostFeature/Source/EditPostComponent.swift
  App/Sources/Feature/EditPostFeature/Source/EditPostView.swift
  App/Sources/Feature/EditPostFeature/Source/EditPostViewModel.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostComponent.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
  App/Sources/Feature/InputPostFeature/Source/InputPostViewModel.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailComponent.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
  App/Sources/Feature/PostDetailFeature/Source/PostDetailViewModel.swift
  App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingView.swift
  App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingViewModel.swift
  App/Sources/Feature/PostListFeature/Sources/PostListView.swift
  App/Sources/Feature/PostListFeature/Sources/PostListViewModel.swift
  Service/Sources/Data/DataSource/Post/RemotePostDataSourceImpl.swift
  Service/Sources/Data/Repository/Post/PostRepositoryImpl.swift
  Service/Sources/Data/UseCase/Post/UpdatePostUseCaseImpl.swift
  Service/Sources/Domain/PostDomain/API/PostAPI.swift
  Service/Sources/Domain/PostDomain/DTO/Request/UpdatePostRequestDTO.swift
  Service/Sources/Domain/PostDomain/DTO/Response/PostDetailResponseDTO.swift
  Service/Sources/Domain/PostDomain/DataSource/RemotePostDataSource.swift
  Service/Sources/Domain/PostDomain/Entity/PostDetailEntity.swift
  Service/Sources/Domain/PostDomain/Repository/PostRepository.swift
  Service/Sources/Domain/PostDomain/UseCase/UpdatePostUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#182 🔀 :: 자격증 - 자격증 등록 페이지 API 연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListView.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListViewModel.swift
  App/Sources/Feature/InputCertificationFeature/Interface/InputCertificationFactory.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationComponent.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationView.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationViewModel.swift
  Service/Sources/Domain/CertificationDomain/DTO/Request/InputCertificationRequestDTO.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#181 🔀 :: [#180] 자격증 - 자격증 등록 페이지 퍼블리싱
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListComponent.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListView.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListViewModel.swift
  App/Sources/Feature/InputCertificationFeature/Interface/InputCertificationFactory.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationComponent.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationView.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationViewModel.swift
  Service/Sources/Domain/CertificationDomain/DTO/Request/InputCertificationRequestDTO.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#177 🔀 :: [#176] 자격증 리스트 페이지 퍼블리싱
  App/Resources/Icon/Icons.xcassets/person.imageset/person.svg
  App/Resources/Icon/Icons.xcassets/person_fill.imageset/Contents.json
  App/Resources/Icon/Icons.xcassets/person_fill.imageset/person.svg
  App/Sources/Application/DI/AppComponent.swift
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/DesignSystem/BottomSheet/AlterBottomSheet.swift
  App/Sources/DesignSystem/View/Row/ListRow.swift
  App/Sources/Feature/ActivityListFeature/ActivityListView.swift
  App/Sources/Feature/CertificationListFeature/Interface/CertificationListFactory.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListComponent.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListView.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListViewModel.swift
  App/Sources/Feature/CertificationListFeature/Source/Component/CertificationListRow.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailComponent.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailView.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailViewModel.swift
  App/Sources/Feature/InputCertificationFeature/Interface/InputCertificationFactory.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationComponent.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationView.swift
  App/Sources/Feature/InputCertificationFeature/Source/InputCertificationViewModel.swift
  App/Sources/Feature/PostListFeature/Sources/PostListView.swift
  Service/Sources/Domain/CertificationDomain/DTO/Request/InputCertificationRequestDTO.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#189 🔀 :: [#184] 공지사항 - 공지사항 페이지 API연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListComponent.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListViewModel.swift
  Service/Sources/Base/Enum/FeedType.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#186 🔀 :: 자격증 리스트 페이지 API 연결
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/CertificationListFeature/Interface/CertificationListFactory.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListComponent.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListView.swift
  App/Sources/Feature/CertificationListFeature/Source/CertificationListViewModel.swift
  App/Sources/Feature/CertificationListFeature/Source/Component/CertificationListRow.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailView.swift
  App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailViewModel.swift
  App/Sources/Feature/ClubListFeature/Source/ClubListComponent.swift
  App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
  App/Sources/Feature/ClubListFeature/Source/ClubListViewModel.swift
  Service/Sources/Domain/CertificationDomain/DTO/Response/CertificationListResponseDTO.swift
  Service/Sources/Domain/CertificationDomain/Entity/CertificationInfoEntity.swift
  Service/Sources/Domain/ClubDomain/DTO/Response/ClubDetailResponseDTO.swift
  Service/Sources/Domain/ClubDomain/Entity/ClubDetailEntity.swift
  Service/Sources/Testing/UseCase/QueryClubDetailUseCaseStub.swift
  Service/Sources/Testing/UseCase/QueryStudentListByClubUseCaseStub.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#185 🔀 :: [#184] 공지사항 - 공지사항 페이지 퍼블리싱
  App/Sources/Application/NeedleGenerated.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListComponent.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
  App/Sources/Feature/NoticeListFeature/Source/NoticeListViewModel.swift
  Service/Sources/Base/Enum/FeedType.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#192 CI 스크립트 verbose 삭제
  .github/workflows/bitgouel-ios-ci.yml
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#191 🔀 :: [#190] inquiry도메인 세팅
  App/Sources/Application/DI/Inquiry/AppComponent+Inquiry.swift
  Service/Sources/Base/BitgouelAPI.swift
  Service/Sources/Base/Enum/AnswerStatusType.swift
  Service/Sources/Data/DataSource/Inquiry/RemoteInquiryDataSourceImpl.swift
  Service/Sources/Data/Repository/Inquiry/InquiryRepositoryImpl.swift
  Service/Sources/Data/UseCase/Inquiry/DeleteInquiryByAdminUseCaseUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/DeleteMyInquiryUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/FetchInquiryByAdminUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/FetchInquiryDetailUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/FetchMyInquiryListUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/InputInquiryUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/ModifyMyInquiryUseCaseImpl.swift
  Service/Sources/Data/UseCase/Inquiry/ReplyInquiryUseCaseImpl.swift
  Service/Sources/Domain/InquiryDomain/API/InquiryAPI.swift
  Service/Sources/Domain/InquiryDomain/DTO/Request/InputInquiryRequestDTO.swift
  Service/Sources/Domain/InquiryDomain/DTO/Response/FetchInquiryDetailResponseDTO.swift
  Service/Sources/Domain/InquiryDomain/DTO/Response/FetchInquiryListResponseDTO.swift
  Service/Sources/Domain/InquiryDomain/DataSource/RemoteInquiryDataSource.swift
  Service/Sources/Domain/InquiryDomain/Entity/InquiryDetailEntity.swift
  Service/Sources/Domain/InquiryDomain/Entity/InquiryInfoEntity.swift
  Service/Sources/Domain/InquiryDomain/Error/InquiryDomainError.swift
  Service/Sources/Domain/InquiryDomain/Repository/InquiryRepository.swift
  Service/Sources/Domain/InquiryDomain/UseCase/DeleteInquiryByAdminUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/DeleteMyInquiryUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/FetchInquiryByAdminUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/FetchInquiryDetailUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/FetchMyInquiryListUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/InputInquiryUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/ModifyMyInquiryUseCase.swift
  Service/Sources/Domain/InquiryDomain/UseCase/ReplyInquiryUseCase.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature
